### ISSUE TITLE
'TypeError: jsdom.jsdom is not a function' in simserver.log

### ISSUE THREAD

**Issue by jsdd25** [minosworld/minos#127]
Hi,

When I run 'python3 -m minos.tools.pygame_client',

I got this error

pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
2018-11-28 10:50:25,089 INFO {'sim_id': 'sim00', 'machine': 'jin-System-Product-Name', 'sim_git_hash': '478f622', 'stk_git_hash': '478f622'}
Starting simulator...
2018-11-28 10:50:25,098 INFO sim00:Starting sim server at /home/jin/minos/minos/server/server.js with port 15961
2018-11-28 10:50:26,102 INFO sim00:sim server has exited with rv 1
2018-11-28 10:50:26,112 WARNING localhost:15961/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=15961): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1543373426104-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1d7451c780>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-11-28 10:50:27,116 WARNING localhost:15961/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=15961): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1543373427114-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1d7451ca90>: Failed to establish a new connection: [Errno 111] Connection refused',))
^CTraceback (most recent call last):
  File "/home/jin/anaconda3/lib/python3.6/site-packages/socketIO_client/logs.py", line 23, in _yield_warning_screen
    yield elapsed_time
Exception: [waiting for connection] HTTPConnectionPool(host='localhost', port=15961): Max retries exceeded with url: /socket.io/?EIO=3&transport=polling&t=1543373427114-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1d7451ca90>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jin/minos/minos/tools/pygame_client.py", line 438, in main
    ep_info = sim.start()
  File "/home/jin/minos/minos/lib/Simulator.py", line 321, in start
    started = self.start_child_servers()
  File "/home/jin/minos/minos/lib/Simulator.py", line 255, in start_child_servers
    self._sio = SocketIO(self.params.host, self.params.port)
  File "/home/jin/anaconda3/lib/python3.6/site-packages/socketIO_client/__init__.py", line 345, in __init__
    resource, hurry_interval_in_seconds, **kw)
  File "/home/jin/anaconda3/lib/python3.6/site-packages/socketIO_client/__init__.py", line 58, in __init__
    self._transport
  File "/home/jin/anaconda3/lib/python3.6/site-packages/socketIO_client/__init__.py", line 66, in _transport
    self._engineIO_session = self._get_engineIO_session()
  File "/home/jin/anaconda3/lib/python3.6/site-packages/socketIO_client/__init__.py", line 86, in _get_engineIO_session
    warning_screen.throw(warning)
  File "/home/jin/anaconda3/lib/python3.6/site-packages/socketIO_client/logs.py", line 29, in _yield_warning_screen
    time.sleep(1)
KeyboardInterrupt
Error running simulator. Aborting.
2018-11-28 10:50:27,887 INFO sim00:Stopping the simulator
2018-11-28 10:50:27,887 INFO Counter()
2018-11-28 10:50:27,888 INFO sim00:Stopping child servers
2018-11-28 10:50:27,888 INFO sim00:Stopped child servers
2018-11-28 10:50:27,888 INFO sim00:Simulator killed.

Does anyone got the same error? How can I solve this? Thank you very much!

**Comment by jsdd25** [comment]
I have fixed this problem. Thank you very much!

**Comment by picksh** [comment]
> I have fixed this problem. Thank you very much!

hi,how did you fix this problem?I have met the same one!
