### ISSUE TITLE
Unable to run 'python3 demo.py --env_config objectgoal_suncg_mf'

### ISSUE THREAD

**Issue by jsdd25** [minosworld/minos#152]
Hello, I wanted to try to run `python3 demo.py --env_config objectgoal_suncg_mf`. However, I encountered the following problem:
```
jin@jin-System-Product-Name:~/minos-0.6.x/gym$ python3 demo.py --env_config objectgoal_suncg_mf
train:87 episodes
test:34 episodes
val:32 episodes
2019-02-08 16:30:41,115 INFO {'sim_id': 'sim00', 'machine': 'jin-System-Product-Name'}
2019-02-08 16:30:41,125 INFO sim00:Starting sim server at /home/jin/minos-0.6.x/gym/minos/server/server.js with port 56493
2019-02-08 16:30:42,453 INFO sim00:connect
2019-02-08 16:30:42,542 INFO sim00:inited
2019-02-08 16:30:42,554 ERROR Error calling start: Error fetching scene /home/jin/work//suncg//house/69e283eec2f85eb53d528dcfb2172ab9/house.json
new_episode(): failure in start/reset
Traceback (most recent call last):
  File "demo.py", line 80, in <module>
    main()
  File "demo.py", line 76, in main
    run_gym(args)
  File "demo.py", line 13, in run_gym
    env.configure(sim_args)
  File "/home/jin/minos-0.6.x/gym/gym_minos/envs/indoor_env.py", line 26, in configure
    self._sim_obs_space = self._sim.get_observation_space(sim_args['outputs'])
  File "/home/jin/minos-0.6.x/gym/minos/lib/RoomSimulator.py", line 227, in get_observation_space
    self.init()
  File "/home/jin/minos-0.6.x/gym/minos/lib/RoomSimulator.py", line 158, in init
    return self.new_episode()
  File "/home/jin/minos-0.6.x/gym/minos/lib/RoomSimulator.py", line 141, in new_episode
    if 'goalObservations' in result:
TypeError: argument of type 'NoneType' is not iterable
2019-02-08 16:30:42,558 INFO sim00:disconnect
2019-02-08 16:30:42,558 INFO sim00:Stopping the simulator
2019-02-08 16:30:42,558 INFO Counter()
2019-02-08 16:30:42,558 INFO sim00:Stopping child servers
2019-02-08 16:30:42,558 INFO sim00:Killing sim pid 9213
2019-02-08 16:30:42,566 INFO sim00:Stopped child servers
2019-02-08 16:30:42,566 INFO sim00:Simulator killed.
```
Then I comment the following two lines:
```
if 'goalObservations' in result:
            del result['goalObservations']
```
However, I still encountered the following errors:
```
jin@jin-System-Product-Name:~/minos-0.6.x/gym$ python3 demo.py --env_config objectgoal_suncg_mf
train:87 episodes
test:34 episodes
val:32 episodes
2019-02-08 16:32:23,475 INFO {'sim_id': 'sim00', 'machine': 'jin-System-Product-Name'}
2019-02-08 16:32:23,483 INFO sim00:Starting sim server at /home/jin/minos-0.6.x/gym/minos/server/server.js with port 28741
2019-02-08 16:32:24,828 INFO sim00:connect
2019-02-08 16:32:24,915 INFO sim00:inited
2019-02-08 16:32:24,926 ERROR Error calling start: Error fetching scene /home/jin/work//suncg//house/69e283eec2f85eb53d528dcfb2172ab9/house.json
new_episode(): failure in start/reset
Running MINOS gym example
Starting episode 0
Traceback (most recent call last):
  File "demo.py", line 80, in <module>
    main()
  File "demo.py", line 76, in main
    run_gym(args)
  File "demo.py", line 17, in run_gym
    observation = env.reset()
  File "/home/jin/anaconda3/lib/python3.6/site-packages/gym/core.py", line 104, in reset
    return self._reset()
  File "/home/jin/minos-0.6.x/gym/gym_minos/envs/indoor_env.py", line 64, in _reset
    res = self._sim.reset()
  File "/home/jin/minos-0.6.x/gym/minos/lib/RoomSimulator.py", line 180, in reset
    output = self._augment_response(observation, None)
  File "/home/jin/minos-0.6.x/gym/minos/lib/RoomSimulator.py", line 207, in _augment_response
    observation = response['observation']
TypeError: 'NoneType' object is not subscriptable
2019-02-08 16:32:24,931 INFO sim00:disconnect
2019-02-08 16:32:24,932 INFO sim00:Stopping the simulator
2019-02-08 16:32:24,932 INFO Counter()
2019-02-08 16:32:24,932 INFO sim00:Stopping child servers
2019-02-08 16:32:24,932 INFO sim00:Killing sim pid 9759
2019-02-08 16:32:24,939 INFO sim00:Stopped child servers
2019-02-08 16:32:24,939 INFO sim00:Simulator killed.
```
Please give me some help!
Thank you very much!

**Comment by angelxuanchang** [comment]
It looks like it's not finding the SUNCG data.  Is your SUNCG data in `/home/jin/work//suncg/` ?  

If it is located in `/xyz/suncg` , you should run 
`NODE_BASE_URL=/xyz python3 demo.py --env_config objectgoal_suncg_mf`
