### ISSUE TITLE
unable to run  "python3 -m minos.tools.pygame_client --source mp3d --scene_ids 2t7WUuJeko7"

### ISSUE THREAD

**Issue by hasifast** [minosworld/minos#40]
I have downloaded the scene id 2t7WUuJeko7 and pasted its folder in matterport dataset subfolders which had the folder with the same name 2t7WUuJeko7.
But when i run the simulator it stops.

ERROR comes out to be:

asad@asad-Inspiron-N5010:~/Desktop/minos$ python3 -m minos.tools.pygame_client --source mp3d --scene_ids 2t7WUuJeko7
2018-04-07 19:17:03,634 INFO {'machine': 'asad-Inspiron-N5010', 'sim_id': 'sim00', 'sim_git_hash': 'be173c1', 'stk_git_hash': 'be173c1'}
Starting simulator...
2018-04-07 19:17:03,675 INFO sim00:Starting sim server at /home/asad/Desktop/minos/minos/server/server.js with port 12977
2018-04-07 19:17:04,696 WARNING localhost:12977/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=12977): Max retries exceeded with url: /socket.io/?transport=polling&EIO=3&t=1523110624687-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7cd37f5198>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-04-07 19:17:05,701 WARNING localhost:12977/socket.io [waiting for connection] HTTPConnectionPool(host='localhost', port=12977): Max retries exceeded with url: /socket.io/?transport=polling&EIO=3&t=1523110625697-0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7cd37a10f0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-04-07 19:17:09,062 INFO sim00:connect
observation_space {'sensors': {'color': BoxSpace(range=[0, 255], shape=[256, 256, 4]), 'force': BoxSpace(range=[None, None], shape=[4, 1])}, 'measurements': {'offset_to_goal': BoxSpace(range=None, shape=[0, 3]), 'direction_to_goal': BoxSpace(range=None, shape=[0, 3]), 'distance_to_goal': BoxSpace(range=None, shape=[0, 1])}}
Simulator started.
***
***
CONTROLS: WASD+Arrows = move agent, R = respawn, N = next state/scene, O = print observation, Q = quit
***
***
episode_info {'sceneId': 'mp3d.2t7WUuJeko7', 'start': {'room': 'R0', 'position': [-0.7394564653134639, 0.5514386199228466, 5.213962124030547], 'angle': 5.282333050982608}, 'task': 'object_goal'}
Traceback (most recent call last):
  File "/home/asad/Desktop/minos/minos/tools/pygame_client.py", line 443, in main
    interactive_loop(sim, args)
  File "/home/asad/Desktop/minos/minos/tools/pygame_client.py", line 377, in interactive_loop
    display_response(response, display_surf, camera_outputs['curr'], print_observation=print_next_observation, write_video=True)
  File "/home/asad/Desktop/minos/minos/tools/pygame_client.py", line 107, in display_response
    draw_offset(measurements.get('offset_to_goal'), display_surf, camera_outputs['offset']['area'])
  File "/home/asad/Desktop/minos/minos/tools/pygame_client.py", line 72, in draw_offset
    dir = (offset[0], offset[2])
IndexError: list index out of range
Error running simulator. Aborting.
2018-04-07 19:17:52,129 INFO sim00:Stopping the simulator
2018-04-07 19:17:52,130 INFO Counter({'frames_received': 2})
2018-04-07 19:17:52,133 INFO sim00:disconnect
2018-04-07 19:17:52,134 INFO sim00:Stopping child servers
2018-04-07 19:17:52,134 INFO sim00:Killing sim pid 8862
2018-04-07 19:17:52,217 INFO sim00:Stopped child servers
2018-04-07 19:17:52,218 INFO sim00:Simulator killed.

**Comment by msavva** [comment]
Hi @hasifast ,
Thank you for trying out MINOS!  This issue might be due to missing data files.  If you include the log files we can help to debug this in detail (see https://github.com/minosworld/minos/blob/master/FAQ.md#reporting-issues).  Please check that you have downloaded and extracted the full SUNCG MINOS data package (see https://github.com/minosworld/minos/issues/39)

**Comment by hasifast** [comment]
[simulator.log](https://github.com/minosworld/minos/files/1887769/simulator.log)
[simserver.log](https://github.com/minosworld/minos/files/1887770/simserver.log)
Log files have been attached.
Please let me know which part of dataset is missing.

**Comment by hasifast** [comment]
please let me know which part o dataset is missing.and send me direct link to download that.
I am trying to run matterport ID 2t7WUuJeko7.
I have downloaded its scan files and copied them in dataset folder of matterport.



Regards,

Haseeb Ahmad

________________________________

**Comment by msavva** [comment]
Thank you for sending the log files. The issue does not appear to be caused by missing data.  It is most likely a bug with the default task configuration (`--task object_goal`).  Please try to run `python3 -m minos.tools.pygame_client --source mp3d --scene_ids 2t7WUuJeko7 --task point_goal` instead and let us know if that works.  That way we can confirm that this is a bug in the task configuration and we will investigate the issue further on our end.
