### ISSUE TITLE
Trouble with running npm install command

### ISSUE THREAD

**Issue by lionminhu** [minosworld/minos#47]
Hello, I have been trying to install MINOS for a while, and I have been following the installation steps in the README.md. However, running `npm install` command inside the `server` directory (located at `/home/mwlee/minos/minos/server` in this case) under `sudo -s` gives the following error message.
```
root@doota:~/mwlee/minos/minos/server# npm install
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/smartscenes/sstk.git /home/.npm/_cacache/tmp/git-clone-33dd48c3
npm ERR! /home/.npm/_cacache/tmp/git-clone-33dd48c3/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2018-04-24T04_47_15_520Z-debug.log
```

Running the command with another `sudo` in front of the command gives a very long error message (more than 4000 lines), and I am not quite sure which part is relevant. The first ~170 lines of this error message is the following.
```
root@doota:~/mwlee/minos/minos/server# sudo npm install
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/smartscenes/sstk.git /home/.npm/_cacache/tmp/git-clone-33dd48c3
npm ERR! /home/.npm/_cacache/tmp/git-clone-33dd48c3/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2018-04-24T04_47_15_520Z-debug.log
root@doota:~/mwlee/minos/minos/server# sudo npm install
loadDep:sstk -> resolveWi | |####################################-----------------------------------------------------------------------------------------------------------------------------------------|
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
loadDep:node-expat -> 304 - |########################################-------------------------------------------------------------------------------------------------------------------------------------|
loadDep:hoek -> resolveWi | |########################################-------------------------------------------------------------------------------------------------------------------------------------|
loadDep:topo -> 304       - |########################################-------------------------------------------------------------------------------------------------------------------------------------|
loadDep:punycode -> 304   - |########################################-------------------------------------------------------------------------------------------------------------------------------------|
loadDep:hoek -> resolveWi / |########################################-------------------------------------------------------------------------------------------------------------------------------------|
loadDep:source-map -> 304 \ |########################################-------------------------------------------------------------------------------------------------------------------------------------|
loadDevDep:pixel-diff ->  | |########################################################---------------------------------------------------------------------------------------------------------------------|
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
loadDep:uuid -> cache add \ |#######################################################################------------------------------------------------------------------------------------------------------|

> node-expat@2.3.16 install /home/mwlee/minos/minos/server/node_modules/node-expat
> node-gyp rebuild

make: Entering directory '/home/mwlee/minos/minos/server/node_modules/node-expat/build'
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
../deps/libexpat/lib/xmlparse.c: In function ‘gather_time_entropy’:
../deps/libexpat/lib/xmlparse.c:780:7: warning: variable ‘gettimeofday_res’ set but not used [-Wunused-but-set-variable]
   int gettimeofday_res;
       ^
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  AR(target) Release/obj.target/deps/libexpat/libexpat.a
  COPY Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
  SOLINK_MODULE(target) Release/obj.target/node_expat.node
  COPY Release/node_expat.node
make: Leaving directory '/home/mwlee/minos/minos/server/node_modules/node-expat/build'

> sstk@0.5.2 postinstall /home/mwlee/minos/minos/server/node_modules/sstk
> npm run bootstrap


> sstk@0.5.2 bootstrap /home/mwlee/minos/minos/server/node_modules/sstk
> lerna bootstrap --hoist

lerna info version 2.10.2
lerna info Bootstrapping 3 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm install
lerna ERR! npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
lerna ERR! WARN engine pixel-diff@1.0.1: wanted: {"npm":">=3.0.0","node":">=4.6.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
lerna ERR! WARN engine express-csv@0.6.0: wanted: {"node":"0.6 || 0.8 || 0.10"} (current: {"node":"4.2.6","npm":"3.5.2"})
lerna ERR! npm WARN deprecated filesaverjs@0.2.2: use 'file-saver' instead
lerna ERR! WARN engine sharp@0.18.4: wanted: {"node":">=4.5.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
lerna ERR! WARN engine najax@1.0.3: wanted: {"node":">= 4.4.3"} (current: {"node":"4.2.6","npm":"3.5.2"})
lerna ERR! npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
lerna ERR! WARN engine joi@13.2.0: wanted: {"node":">=8.9.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
lerna ERR! WARN engine hoek@5.0.3: wanted: {"node":">=8.9.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
lerna ERR! WARN engine topo@3.0.0: wanted: {"node":">=8.0.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
lerna ERR! WARN engine punycode@2.1.0: wanted: {"node":">=6"} (current: {"node":"4.2.6","npm":"3.5.2"})
lerna ERR! WARN engine hoek@5.0.3: wanted: {"node":">=8.9.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
lerna ERR! WARN engine source-map@0.7.2: wanted: {"node":">= 8"} (current: {"node":"4.2.6","npm":"3.5.2"})
lerna ERR! WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"4.2.6","npm":"3.5.2"})
lerna ERR! npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
lerna ERR! WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"4.2.6","npm":"3.5.2"})
lerna ERR! WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"4.2.6","npm":"3.5.2"})
lerna ERR! WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"4.2.6","npm":"3.5.2"})
lerna ERR! WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"4.2.6","npm":"3.5.2"})
lerna ERR! WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"4.2.6","npm":"3.5.2"})
lerna ERR! WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"4.2.6","npm":"3.5.2"})
lerna ERR! WARN engine hawk@6.0.2: wanted: {"node":">=4.5.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
lerna ERR! npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
lerna ERR! npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
lerna ERR! npm WARN deprecated jscs-preset-wikimedia@1.0.1: Deprecated in favour of eslint-config-wikimedia. -- https://phabricator.wikimedia.org/T118941
lerna ERR! npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
lerna ERR! npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
lerna ERR! npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
lerna ERR! npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
lerna ERR! npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
lerna ERR! WARN engine tar@3.2.1: wanted: {"node":">=4.5"} (current: {"node":"4.2.6","npm":"3.5.2"})
lerna ERR! npm WARN prefer global npm@5.8.0 should be installed with -g
lerna ERR! npm WARN prefer global jsonlint@1.6.3 should be installed with -g
lerna ERR! npm WARN prefer global node-gyp@3.6.2 should be installed with -g
lerna ERR! ../deps/libexpat/lib/xmlparse.c: In function ‘gather_time_entropy’:
lerna ERR! ../deps/libexpat/lib/xmlparse.c:780:7: warning: variable ‘gettimeofday_res’ set but not used [-Wunused-but-set-variable]
lerna ERR!    int gettimeofday_res;
lerna ERR!        ^
lerna ERR! prebuild-install WARN install No prebuilt binaries found (target=9.8.0 runtime=node arch=x64 platform=linux)
lerna ERR! In file included from ../angle/src/compiler/preprocessor/DirectiveParser.cpp:17:0:
lerna ERR! ../angle/src/compiler/preprocessor/MacroExpander.h:86:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
lerna ERR!      std::auto_ptr<Token> mReserveToken;
lerna ERR!           ^
lerna ERR! In file included from /usr/include/c++/5/memory:81:0,
lerna ERR!                  from ../angle/src/compiler/preprocessor/MacroExpander.h:11,
lerna ERR!                  from ../angle/src/compiler/preprocessor/DirectiveParser.cpp:17:
lerna ERR! /usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
lerna ERR!    template<typename> class auto_ptr;
lerna ERR!                             ^
lerna ERR! In file included from ../angle/src/compiler/preprocessor/MacroExpander.cpp:7:0:
lerna ERR! ../angle/src/compiler/preprocessor/MacroExpander.h:86:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
lerna ERR!      std::auto_ptr<Token> mReserveToken;
lerna ERR!           ^
lerna ERR! In file included from /usr/include/c++/5/memory:81:0,
lerna ERR!                  from ../angle/src/compiler/preprocessor/MacroExpander.h:11,
lerna ERR!                  from ../angle/src/compiler/preprocessor/MacroExpander.cpp:7:
lerna ERR! /usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
lerna ERR!    template<typename> class auto_ptr;
lerna ERR!                             ^
lerna ERR! In file included from ../angle/src/compiler/preprocessor/Preprocessor.cpp:14:0:
lerna ERR! ../angle/src/compiler/preprocessor/MacroExpander.h:86:10: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
lerna ERR!      std::auto_ptr<Token> mReserveToken;
lerna ERR!           ^
lerna ERR! In file included from /usr/include/c++/5/memory:81:0,
lerna ERR!                  from ../angle/src/compiler/preprocessor/MacroExpander.h:11,
lerna ERR!                  from ../angle/src/compiler/preprocessor/Preprocessor.cpp:14:
lerna ERR! /usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
lerna ERR!    template<typename> class auto_ptr;
lerna ERR!                             ^
lerna ERR! Error: Running Homebrew as root is extremely dangerous and no longer supported.
lerna ERR! As Homebrew does not drop privileges on installation you would be giving all
lerna ERR! build scripts full access to your system.
lerna ERR! /bin/sh: 1: eval: W:: not found
lerna ERR! gyp: Call to 'which brew >/dev/null 2>&1 && eval $(brew --env) && echo $PKG_CONFIG_LIBDIR || true' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
lerna ERR! gyp ERR! configure error 
lerna ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
lerna ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/mwlee/minos/minos/server/node_modules/sstk/node_modules/node-gyp/lib/configure.js:336:16)
lerna ERR! gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
lerna ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
lerna ERR! gyp ERR! System Linux 4.4.0-119-generic
lerna ERR! gyp ERR! command "/usr/local/bin/node" "/home/mwlee/minos/minos/server/node_modules/sstk/node_modules/.bin/node-gyp" "rebuild"
lerna ERR! gyp ERR! cwd /home/mwlee/minos/minos/server/node_modules/sstk/node_modules/sharp
lerna ERR! gyp ERR! node -v v9.8.0
lerna ERR! gyp ERR! node-gyp -v v3.6.2
lerna ERR! gyp ERR! not ok 
lerna ERR! npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
lerna ERR! npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.2
lerna ERR! npm WARN sstk No repository field.
lerna ERR! npm WARN sstk No license field.
lerna ERR! npm ERR! Linux 4.4.0-119-generic
lerna ERR! npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
lerna ERR! npm ERR! node v4.2.6
lerna ERR! npm ERR! npm  v3.5.2
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! 
lerna ERR! npm ERR! sharp@0.18.4 install: `node-gyp rebuild`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR! 
lerna ERR! npm ERR! Failed at the sharp@0.18.4 install script 'node-gyp rebuild'.
lerna ERR! npm ERR! Make sure you have the latest version of node.js and npm installed.
lerna ERR! npm ERR! If you do, this is most likely a problem with the sharp package,
lerna ERR! npm ERR! not with npm itself.
lerna ERR! npm ERR! Tell the author that this fails on your system:
lerna ERR! npm ERR!     node-gyp rebuild
lerna ERR! npm ERR! You can get information on how to open an issue for this project with:
lerna ERR! npm ERR!     npm bugs sharp
lerna ERR! npm ERR! Or if that isn't available, you can get their info via:
lerna ERR! npm ERR!     npm owner ls sharp
lerna ERR! npm ERR! There is likely additional logging output above.
lerna ERR! 
lerna ERR! npm ERR! Please include the following file with any support request:
lerna ERR! npm ERR!     /home/mwlee/minos/minos/server/node_modules/sstk/npm-debug.log
```

I have Node v9.11.1, and `npm version` gives the following result.
```
root@doota:~/mwlee/minos/minos/server# npm version
{ 'sstk-sim': '0.5.2',
  npm: '5.6.0',
  ares: '1.13.0',
  cldr: '33.0',
  http_parser: '2.8.0',
  icu: '61.1',
  modules: '59',
  napi: '3',
  nghttp2: '1.29.0',
  node: '9.11.1',
  openssl: '1.0.2o',
  tz: '2018c',
  unicode: '10.0',
  uv: '1.19.2',
  v8: '6.2.414.46-node.23',
  zlib: '1.2.11' }
```
If there are other information I would need to provide, or if I would have to raise this issue in npm repository instead, please let me know.

**Comment by msavva** [comment]
@lionminhu Thank you for trying out MINOS.
The log indicates the issue is with permissions during git cloning of the dependencies.  There should be no need to run any of the installation steps using `sudo`.  Can you confirm whether you installed `nvm` and run `npm install` under a regular user account, not using sudo?  If you perform all the installation steps from beginning to end without elevating to a sudo user there should be no issue like the one you see.

**Comment by msavva** [comment]
@lionminhu Besides the permissions issues, at the end of the log it looks like you might also be missing a package for building one of the dependencies. In Ubuntu you can install necessary packages for building all dependencies using `sudo apt-get install build-essential libxi-dev libglu1-mesa-dev libglew-dev libvips`.

**Comment by lionminhu** [comment]
Uninstalling and reinstalling `nvm` and rerunning `npm install` without `sudo` seems to have worked successfully. I installed `libvips` package, which was the only one missing, according to your advice.

I have yet to check that everything works after installing the SUNCG/Matterport3D data set, but since `npm install` part is settled, I will close this issue now.

Thank you for your help.
